spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  liquibase:
    user: sa
    password:
    url: jdbc:h2:mem:/testdb;DB_CLOSE_DELAY=-1

password:
  encoder:
    secret: mysecret
    iteration: 33
    keylength: 256
jwt:
  secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
  expiration: 28800

info:
  app:
    name: Quiz
    description: This is my first spring boot application
    version: 1.0.0